### ISSUE TITLE
false and zero error

### ISSUE THREAD

**Issue by jesus101037** [Spyna/react-context-hook#13]
I hava set a store with an initial state ```{ logIn: false, counter: 0 }``` but when I use the ```useStoreValue('logIn')``` or ```useStoreValue('counter')``` the result is ```undefined```. Is this the expected behavior?

**Comment by Spyna** [comment]
This is actually a bug, I'm going to correct it right now

**Comment by Spyna** [comment]
thank you for taking the time to notice this issue.
this issue is fixed with version v2.1.1
