### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mwit-a** [Spyna/react-context-hook#2]
Hi @Spyna 

Awesome library, could you provide @types to use the library in typescript react projects.

Thanks in advance, Marc

**Comment by vandijkstef** [comment]
While your module is interesting, I found it wasn't for my use case.

I did see you've been adding typing through JSdoc, this might come in handy: https://voxpelli.com/2019/10/use-type-script-3-7-to-generate/

**Comment by Spyna** [comment]
Thank you for the hint, I'll take a look

**Comment by jayp0521** [comment]
+1 would be really helpful

**Comment by jjmorga** [comment]
+1 would love Typescript Support

**Comment by Spyna** [comment]
Typescript support added in release 3.0.4

**Comment by jjmorga** [comment]
Cannot get to properly compile, getting error : 

TypeError: Cannot read property 'store' of null


src/useStore.js:10
   7 |   return a === b
   8 | }
   9 | 
> 10 | function useSelector(stateSelectorFn) {
  11 |   const [, forceRender] = useReducer((s) => s + 1, 0)
  12 |   const { store } = useContext(StoreContext)
  13 |   const latestStateSelectorFn = useRef()

**Comment by RaddishIoW** [comment]
I'm not sure that's related to the typescript definitions, unless it's an error that's been highlighted by the type checking?
That error looks to me like a problem somewhere with the `useContext` hook provided by react...? It's difficult to say without seeing more context about the issue.
