### ISSUE TITLE
'useGetAndset' naming convention

### ISSUE THREAD

**Issue by edilsalvador** [Spyna/react-context-hook#3]
The title explains for itself :sweat_smile: 
Though it's really not a big deal it just annoys me when using it to the point I change its name when exporting HAHA

`export { useGetAndset as useGetAndSet } from 'react-context-hook';`

**Comment by Spyna** [comment]
Many thanks for taking the time to notice me. 
I just released version 1.2.1 https://github.com/Spyna/react-context-hook/releases/tag/v1.2.1 with the correct hook name
In order to provide backward compatibility, the old hook still exists but will be removed in the next minor version.

**Comment by edilsalvador** [comment]
Thanks, will update my code then!
