### ISSUE TITLE
TypeError: react_context_hook__WEBPACK_IMPORTED_MODULE_4__.store.get is not a function

### ISSUE THREAD

**Issue by yelnyaface** [Spyna/react-context-hook#38]
Hi, I am currently getting this error for:

```
import { useStore, withStore, store } from 'react-context-hook';

    // IF 'searchData' Exist
    if(store.get('searchData')) {

        genres      = store.get('searchData').genres;
        tags        = store.get('searchData').tags;
        artists     = store.get('searchData').artists;
        characters  = store.get('searchData').characters;
        parodies    = store.get('searchData').parodies;

    }
 ```

 
![Screenshot_49](https://user-images.githubusercontent.com/16500322/113104300-f3b9eb00-9232-11eb-9fa9-b1e6cd3c62fe.png)

any idea what I did wrong?

**Comment by Spyna** [comment]
Yes, 
the function `get` does not exists in the store object. 
You could use the function `getState()` to access the whole state, but I suggest you use the hooks that this library provides: https://github.com/Spyna/react-context-hook#usage
