### ISSUE TITLE
Does it supports memoization by default like connect in Redux?

### ISSUE THREAD

**Issue by fruity4pie** [Spyna/react-context-hook#46]
Hello, 👋 

Does it work from the hood like the Redux connect function? Or I also should provide equality functions then function(library hooks) didn't do unnecessary re-rendering??

https://react-redux.js.org/api/hooks#performance
https://react-redux.js.org/api/hooks#hooks-recipes

**Comment by Spyna** [comment]
Yes, it does :smiley: and no, it does not trigger unnecessary re-rendering.
You can play with the demo that demonstrates this: https://spyna.github.io/react-context-hook/
If interested, take a look at the source code: https://github.com/Spyna/react-context-hook/blob/master/src/useStore.js#L10;L32
