### ISSUE TITLE
[Bug] useStoreValue return type is incorrect

### ISSUE THREAD

**Issue by jayp0521** [Spyna/react-context-hook#57]
The type for `useStoreValue return` is incorrect. It should be `T | typeof defaultValue`. Could this be fixed?

https://github.com/Spyna/react-context-hook/blob/9a387d27b3caae23f4a1f04b5a3433cacd7a30b9/src/useStore.js#L198-L202

**Comment by Spyna** [comment]
Sure, it will be fixed asap

**Comment by Spyna** [comment]
fixed in v3.0.7
