### ISSUE TITLE
Is there a way of preserving the store after page refresh?

### ISSUE THREAD

**Issue by ianpierreg** [Spyna/react-context-hook#6]
Just like redux `redux-persist` and `redux-storage` middlewares

**Comment by Spyna** [comment]
You can use the **store listener** that is notified each time any value in the store changes. 
The listener can persist to wherever you want: localStorage, local DB, cache, call an API, and so on.

Here a very basic example using localStorage, that writes the store to localStorage each time it changes. And read the initial value of the store from localStorage.

```JS
const THE_STORE = "THE_STORE";

function persistOnChange(store) {
   //do something before persisting: eg: delete store['tmp.data']
   localStorage.setItem(THE_STORE, JSON.stringify(store));
}

const storeConfig = {
  listener: persistOnChange
}

const initialState = JSON.read(localStorage.getItem(THE_STORE) || {});

export default withStore(App, initialState, storeConfig)
```
