### ISSUE TITLE
Loop in useEffet hook while modifying my store value

### ISSUE THREAD

**Issue by donadoamaia** [Spyna/react-context-hook#7]
Hi !

First of all, nice library, I love it !

However, I'm trying to modify my store value in my useEffect Hook and I have a loop as response.
Here my exemple :
```
const [server, setServer] = useGetAndSet("server");

  useEffect(() => {
    const getInfoServer = async () => {
        const response= await callApi("get", "servers/default", null, {
        id: user
      });
      setServeur(response.data.server);
    };
    getInfoServeur();
  }, []);
```

Do you have any idea how can I set my value without having this side effect ?
Thanks !

**Comment by Spyna** [comment]
Hi, 
the code example you provide does not loop, because the effect runs only once (because of the empty dependency array specified with `[]` ). 

It loops if you remove the dependency array from the useEffect hook. 

Could you please provide a code snippet that loops, so I can reproduce this issue. 
Thank you

**Comment by donadoamaia** [comment]
In fact, it does loop.
If I do not modify my store value 'server', the useEffect is called only one.
But if I do modify my store value 'server' with the setServer fonction, my application has a nasty loop.
I really do not understand the issue cause with the [ ] I do not have loop problems, only when I call the set fonction inside.

**Comment by donadoamaia** [comment]
In fact ,it does loop.
I have done some tests and if I set my store value inside my useEffect, I have no problem.
However, if I do it inside my async fonction,after the call to the API, I get the nasty loop in my application.

**Comment by Spyna** [comment]
@donadoamaia  Could you upgrade this package to the latest version? To see if the issue is resolved?
