### ISSUE TITLE
Need updateSetValue

### ISSUE THREAD

**Issue by matinfo** [Spyna/react-context-hook#8]
One missing method hook be **updateSetValue**. To update juste part of stored object

**Comment by Spyna** [comment]
What would be the hook signature? Something like this? 
```
updateSetValue(key, propertyToUpdate, value) 
```

I have a few questions: 
Why not update the whole value using `setValue` that could be read as "what are the benefits of using this new hook?"

**Comment by matinfo** [comment]
@Spyna I use your context state hooks on my project, and thanks work pretty well!
My request was to be able to update only part of the object attributs, when I do a PATCH that update only one attribut for example. But you have right I be able to manage such scenario on my side, by doing, first get object, next update the concerned attribut, next set object.
